{
  imports = [
    ./browser
    ./catppuccin.nix
    ./codium.nix
    ./cursors.nix
    ./direnv.nix
    ./eza.nix
    ./fd.nix
    ./fuzzel.nix
    ./fzf.nix
    ./gh.nix
    ./git.nix
    ./gtk.nix
    ./keepassxc.nix
    ./lazygit.nix
    ./mpv.nix
    ./music.nix
    ./neovim
    ./nemo.nix
    ./office.nix
    ./oh-my-posh
    ./sway
    ./terminal
    ./qt.nix
    ./ripgrep.nix
    ./zsh
    ./zoxide.nix
  ];
}